#!/bin/bash
set -e
cd ~/.vim_runtime

PLUGSLUGS=(`cat "yardasol_plugslugs.txt"`)
for plugslug in ${PLUGSLUGS[@]}
do
    IFS='/'
    read -ra arr <<< "$plugslug"
    author=${arr[0]}
    plugin=${arr[1]}
    git clone https://github.com/$author/$plugin my_plugins/$plugin
done

# add ultisnips
ln -s ../../yardasol_snippets my_plugins/ultisnips/UltiSnips

echo '" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/yardasol_configs.vim
#source ~/.vim_runtime/vimrcs/plugins_config.vim
#source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry' > ~/.vimrc

echo "Installed the yardasol Vim configuration successfully! Enjoy :-)"
